
module.exports = {
  1: ' Generic error ',
  2: ' Internal logic error in SQLite ',
  3: ' Access permission denied ',
  4: ' Callback routine requested an abort ',
  5: ' The database file is locked ',
  6: ' A table in the database is locked ',
  7: ' A malloc() failed ',
  8: ' Attempt to write a readonly database ',
  9: ' Operation terminated by sqlite3_interrupt()',
  10: ' Some kind of disk I/O error occurred ',
  11: ' The database disk image is malformed ',
  12: ' Unknown opcode in sqlite3_file_control() ',
  13: ' Insertion failed because database is full ',
  14: ' Unable to open the database file ',
  15: ' Database lock protocol error ',
  16: ' Internal use only ',
  17: ' The database schema changed ',
  18: ' String or BLOB exceeds size limit ',
  19: ' Abort due to constraint violation ',
  20: ' Data type mismatch ',
  21: ' Library used incorrectly ',
  22: ' Uses OS features not supported on host ',
  23: ' Authorization denied ',
  24: ' Not used ',
  25: ' 2nd parameter to sqlite3_bind out of range ',
  26: ' File opened that is not a database file ',
  27: ' Notifications from sqlite3_log() ',
  28: ' Warnings from sqlite3_log() ',
  100: ' sqlite3_step() has another row ready ',
  101: ' sqlite3_step() has finished executing ',
};
